
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_NANO(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		     [1:0]		DRAM_DQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_WE_N,

	//////////// EPCS //////////
	output		          		EPCS_ASDO,
	input 		          		EPCS_DATA0,
	output		          		EPCS_DCLK,
	output		          		EPCS_NCSO,

	//////////// Accelerometer and EEPROM //////////
	output		          		G_SENSOR_CS_N,
	input 		          		G_SENSOR_INT,
	output		          		I2C_SCLK,
	inout 		          		I2C_SDAT,

	//////////// ADC //////////
	output		          		ADC_CS_N,
	output		          		ADC_SADDR,
	output		          		ADC_SCLK,
	input 		          		ADC_SDAT,

	//////////// 2x13 GPIO Header //////////
	inout 		    [12:0]		GPIO_2,
	input 		     [2:0]		GPIO_2_IN,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [33:0]		GPIO_0,
	input 		     [1:0]		GPIO_0_IN,

	//////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
	inout 		    [33:0]		GPIO_1,
	input 		     [1:0]		GPIO_1_IN
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================
reg [31:0] test_counter = 32'b0;
always @(posedge CLOCK_50) begin
	test_counter = test_counter + 1;
end

assign LED[6:4] = test_counter[31-4:31-7];

wire clk_28m;
wire clk_14m;
wire clk_07m;

reg [2:0] clk = 0;
always @(posedge clk_28m) begin
	clk = clk + 1;
end
assign clk_14m = clk[0];
assign clk_07m = clk[1];


assign GPIO_0[0] = clk_07m;

pll14m my_pll14m (
        .areset(~KEY[0]),
        .inclk0(CLOCK_50),    
        .c0(clk_28m),
		  .locked(LED[7])
    );

wire [10:0] x_video;
wire [10:0] y_video;

video_sync_gen my_video_sync_gen (
        .reset(~KEY[0]),
        .clk(clk_14m),    
        .h_sync(GPIO_0[1]),
		  .v_sync(GPIO_0[2]),
		  .active_video(GPIO_0[3]),
		  .x_pos(x_video),
		  .y_pos(y_video)
    );

	 
dual_port_video_ram my_dual_port_video_ram(
			.clk(clk_28m),
			.we_a(clk_07m),
			
			.addr_a(y_video),
			.data_a(y_video),
			
			.addr_b(x_video),
			.data_b(LED[3:0])
	);
endmodule
