//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_NANO(

    //////////// CLOCK //////////
    input                CLOCK_50,

    //////////// LED //////////
    output        [7:0]    LED,

    //////////// KEY //////////
    input         [1:0]    KEY,

    //////////// SW //////////
    input         [3:0]    SW,

    //////////// SDRAM //////////
    output        [12:0]    DRAM_ADDR,
    output         [1:0]    DRAM_BA,
    output                DRAM_CAS_N,
    output                DRAM_CKE,
    output                DRAM_CLK,
    output                DRAM_CS_N,
    inout         [15:0]    DRAM_DQ,
    output         [1:0]    DRAM_DQM,
    output                DRAM_RAS_N,
    output                DRAM_WE_N,

    //////////// EPCS //////////
    output                EPCS_ASDO,
    input                EPCS_DATA0,
    output                EPCS_DCLK,
    output                EPCS_NCSO,

    //////////// Accelerometer and EEPROM //////////
    output                G_SENSOR_CS_N,
    input                G_SENSOR_INT,
    output                I2C_SCLK,
    inout                I2C_SDAT,

    //////////// ADC //////////
    output                ADC_CS_N,
    output                ADC_SADDR,
    output                ADC_SCLK,
    input                ADC_SDAT,

    //////////// 2x13 GPIO Header //////////
    inout         [12:0]    GPIO_2,
    input         [2:0]    GPIO_2_IN,

    //////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
    inout         [33:0]    GPIO_0,
    input         [1:0]    GPIO_0_IN,

    //////////// GPIO_1, GPIO_1 connect to GPIO Default //////////
    inout         [33:0]    GPIO_1,
    input         [1:0]    GPIO_1_IN
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire clk_28m;
wire clk_14m;
wire clk_07m;

reg [31:0] test_counter = 32'b0;
always @(posedge CLOCK_50) begin
    test_counter <= test_counter + 1;
end

assign LED[6:4] = test_counter[26:24];

pll14m my_pll14m (
    .areset(~KEY[0]),
    .inclk0(CLOCK_50),
    .c0(clk_28m),
    .locked(LED[7])
);

reg [2:0] clk_div = 0;
always @(posedge clk_28m) begin
    clk_div <= clk_div + 1;
end
assign clk_14m = clk_div[0];
assign clk_07m = clk_div[1];


wire [14:0] pix_pos;
wire active_video;
wire h_sync;
wire v_sync;

// Переопределение параметров синхрогенератора для разрешения 320x200
video_sync_gen #(
    .H_ACTIVE(320),
    .H_FP(32),
    .H_SYNC(33),
    .H_BP(63),
    .H_TOTAL(448),
    .V_ACTIVE(200),
    .V_FP(46),
    .V_SYNC(25),
    .V_BP(24),
    .V_TOTAL(312)
) my_video_sync_gen (
    .reset(~KEY[0]),
    .clk(clk_14m),
    .h_sync(h_sync),
    .v_sync(v_sync),
    .active_video(active_video),
    .pix_pos(pix_pos)
);

// Вычисление адреса для чтения из видеопамяти
wire [15:0] video_addr;
assign video_addr = pix_pos[14:1];

wire [7:0] video_data;

// Регистры для записи в видеопамять
reg [15:0] write_addr;
reg [7:0] write_data;
reg we_a;
reg [31:0] frame_counter;
reg [15:0] line_num_reg; // Регистр для номера строки

// Генерация паттерна и запись в видеопамять
always @(posedge clk_07m or negedge KEY[0]) begin
    if (~KEY[0]) begin
        write_addr <= 0;
        we_a <= 0;
        frame_counter <= 0;
        line_num_reg <= 0;
    end else begin
        // Увеличиваем счетчик кадров
        frame_counter <= frame_counter + 1;
        
        // Всегда разрешаем запись
        we_a <= 1;
        
        // Инкрементируем адрес записи
        write_addr <= write_addr + 1;
        
        // Обновляем номер строки на основе адреса записи
        if (write_addr < 32000) begin
            if (write_addr[7:0] == 159) begin
                line_num_reg <= line_num_reg + 1;
            end
        end else begin
            line_num_reg <= 0;
        end
        
        if (write_addr == 0) begin
            line_num_reg <= 0;
        end
        
        // Генерация данных для записи в зависимости от номера строки
        if (write_addr < 32000) begin
            case (line_num_reg)
                16'd1: write_data <= 8'hFF; // Белая строка (два белых пикселя)
                16'd3: write_data <= 8'h99; // Красная строка (два красных пикселя)
                16'd5: write_data <= 8'h33; // Синяя строка (два синих пикселя)
                default: write_data <= 8'h00; // Черная строка
            endcase
        end else begin
            write_data <= 8'h00; // За пределами активной области - черный
        end
    end
end

// Двухпортовая видеопамять
dual_port_video_ram my_dual_port_video_ram(
    .clk(clk_28m),
    .we_a(we_a),
    .addr_a(write_addr),
    .data_a(write_data),
    .addr_b(video_addr),
    .data_b(video_data)
);

// Извлечение пикселя из байта видеопамяти
wire [3:0] pixel = pix_pos[0] ? video_data[3:0] : video_data[7:4];

// Формирование VGA сигналов (RGBI в формате 4 бита: R, G, B, I)
assign GPIO_0[3:2] = {pixel[0], pixel[3]}; // R
assign GPIO_0[5:4] = {pixel[0], pixel[2]}; // G
assign GPIO_0[7:6] = {pixel[0], pixel[1]}; // B

assign GPIO_0[0] = h_sync ^ ~v_sync;

endmodule